"""trace deletion sync runs

Revision ID: 323df06d1e7a
Revises: 4673d60c0132
Create Date: 2026-08-05 22:40:21.329615
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "323df06d1e7a"
down_revision: str | None = "4673d60c0132"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exercise_templates", sa.Column("deleted_sync_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_exercise_templates_deleted_sync_id_sync_runs"),
        "exercise_templates",
        "sync_runs",
        ["deleted_sync_id"],
        ["id"],
    )
    op.add_column("hevy_users", sa.Column("deleted_sync_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_hevy_users_deleted_sync_id_sync_runs"),
        "hevy_users",
        "sync_runs",
        ["deleted_sync_id"],
        ["id"],
    )
    op.add_column("routines", sa.Column("deleted_sync_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_routines_deleted_sync_id_sync_runs"),
        "routines",
        "sync_runs",
        ["deleted_sync_id"],
        ["id"],
    )
    op.add_column("workouts", sa.Column("deleted_sync_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_workouts_deleted_sync_id_sync_runs"),
        "workouts",
        "sync_runs",
        ["deleted_sync_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_workouts_deleted_sync_id_sync_runs"), "workouts", type_="foreignkey"
    )
    op.drop_column("workouts", "deleted_sync_id")
    op.drop_constraint(
        op.f("fk_routines_deleted_sync_id_sync_runs"), "routines", type_="foreignkey"
    )
    op.drop_column("routines", "deleted_sync_id")
    op.drop_constraint(
        op.f("fk_hevy_users_deleted_sync_id_sync_runs"), "hevy_users", type_="foreignkey"
    )
    op.drop_column("hevy_users", "deleted_sync_id")
    op.drop_constraint(
        op.f("fk_exercise_templates_deleted_sync_id_sync_runs"),
        "exercise_templates",
        type_="foreignkey",
    )
    op.drop_column("exercise_templates", "deleted_sync_id")
    # ### end Alembic commands ###
