"""create normalized hevy schema

Revision ID: 4673d60c0132
Revises:
Create Date: 2026-08-05 22:36:43.858359
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4673d60c0132"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inserted_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("unchanged_count", sa.Integer(), nullable=False),
        sa.Column("deleted_count", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    op.create_table(
        "exercise_templates",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("exercise_type", sa.String(length=64), nullable=False),
        sa.Column("primary_muscle_group", sa.String(length=64), nullable=False),
        sa.Column("equipment", sa.String(length=64), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_sync_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_seen_sync_id"],
            ["sync_runs.id"],
            name=op.f("fk_exercise_templates_last_seen_sync_id_sync_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_templates")),
        sa.UniqueConstraint("external_id", name=op.f("uq_exercise_templates_external_id")),
    )
    op.create_table(
        "hevy_users",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("profile_url", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_sync_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_seen_sync_id"],
            ["sync_runs.id"],
            name=op.f("fk_hevy_users_last_seen_sync_id_sync_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hevy_users")),
        sa.UniqueConstraint("external_id", name=op.f("uq_hevy_users_external_id")),
    )
    op.create_table(
        "routines",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_sync_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_seen_sync_id"],
            ["sync_runs.id"],
            name=op.f("fk_routines_last_seen_sync_id_sync_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routines")),
        sa.UniqueConstraint("external_id", name=op.f("uq_routines_external_id")),
    )
    op.create_table(
        "workouts",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("routine_external_id", sa.String(length=128), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_sync_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_seen_sync_id"],
            ["sync_runs.id"],
            name=op.f("fk_workouts_last_seen_sync_id_sync_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workouts")),
        sa.UniqueConstraint("external_id", name=op.f("uq_workouts_external_id")),
    )
    op.create_table(
        "exercise_template_secondary_muscles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("template_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("muscle_group", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["exercise_templates.id"],
            name=op.f("fk_exercise_template_secondary_muscles_template_id_exercise_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_template_secondary_muscles")),
        sa.UniqueConstraint(
            "template_id",
            "position",
            name=op.f("uq_exercise_template_secondary_muscles_template_id"),
        ),
    )
    op.create_table(
        "routine_exercises",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("routine_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("exercise_template_external_id", sa.String(length=128), nullable=False),
        sa.Column("superset_id", sa.Integer(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["routine_id"],
            ["routines.id"],
            name=op.f("fk_routine_exercises_routine_id_routines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routine_exercises")),
        sa.UniqueConstraint("routine_id", "position", name=op.f("uq_routine_exercises_routine_id")),
    )
    op.create_table(
        "workout_exercises",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("workout_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("exercise_template_external_id", sa.String(length=128), nullable=False),
        sa.Column("superset_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name=op.f("fk_workout_exercises_workout_id_workouts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_exercises")),
        sa.UniqueConstraint("workout_id", "position", name=op.f("uq_workout_exercises_workout_id")),
    )
    op.create_table(
        "routine_sets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("routine_exercise_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("set_type", sa.String(length=32), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("distance_meters", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("custom_metric", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("rep_range_start", sa.Integer(), nullable=True),
        sa.Column("rep_range_end", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["routine_exercise_id"],
            ["routine_exercises.id"],
            name=op.f("fk_routine_sets_routine_exercise_id_routine_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routine_sets")),
        sa.UniqueConstraint(
            "routine_exercise_id", "position", name=op.f("uq_routine_sets_routine_exercise_id")
        ),
    )
    op.create_table(
        "workout_sets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("workout_exercise_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("set_type", sa.String(length=32), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("distance_meters", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("custom_metric", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["workout_exercise_id"],
            ["workout_exercises.id"],
            name=op.f("fk_workout_sets_workout_exercise_id_workout_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_sets")),
        sa.UniqueConstraint(
            "workout_exercise_id", "position", name=op.f("uq_workout_sets_workout_exercise_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_sets")
    op.drop_table("routine_sets")
    op.drop_table("workout_exercises")
    op.drop_table("routine_exercises")
    op.drop_table("exercise_template_secondary_muscles")
    op.drop_table("workouts")
    op.drop_table("routines")
    op.drop_table("hevy_users")
    op.drop_table("exercise_templates")
    op.drop_table("sync_runs")
    # ### end Alembic commands ###
